# Generated by Django 4.2.7 on 2023-12-01 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=500)),
                ('idade', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=500)),
                ('cpf', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=500)),
                ('quantQuarto', models.PositiveIntegerField(default=0)),
                ('localizacao', models.CharField(default=0, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('numero', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('camasSolteiro', models.PositiveIntegerField()),
                ('camasCasal', models.PositiveIntegerField()),
                ('idHotel', models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, to='APP.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('dataEntrada', models.DateField(default=0)),
                ('dataSaida', models.DateField(default=0)),
                ('emAtividade', models.BooleanField(default=False)),
                ('id_Hotel', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='APP.hotel')),
                ('id_cliente', models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, to='APP.cliente')),
                ('id_quarto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='APP.quarto')),
            ],
        ),
    ]
