# Generated by Django 4.2.7 on 2023-11-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=500)),
                ('idade', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('numero', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('camasSolteiro', models.PositiveIntegerField()),
                ('camasCasal', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MinhaTabela',
        ),
    ]
