# Generated by Django 4.2.7 on 2023-12-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_funcionario_senha_alter_funcionario_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='ocupado',
            field=models.BooleanField(default=False),
        ),
    ]
