# Generated by Django 4.2.7 on 2023-12-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_quarto_ocupado'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='temQuarto',
            field=models.BooleanField(default=False),
        ),
    ]
