# Generated by Django 4.2.7 on 2023-12-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_hotel_temquarto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
