# Generated by Django 4.2.7 on 2023-12-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_delete_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('senha', models.CharField(max_length=200)),
            ],
        ),
    ]
