# Generated by Django 2.2.20 on 2023-12-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='id',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(editable=False, max_length=11, primary_key=True, serialize=False),
        ),
    ]
