# Generated by Django 2.2.20 on 2023-12-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_auto_20231211_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(editable=False, max_length=12, primary_key=True, serialize=False),
        ),
    ]
