# Generated by Django 2.2.20 on 2023-12-12 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0010_auto_20231212_1745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.RemoveField(
            model_name='quarto',
            name='idHotel',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_Hotel',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_quarto',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Quarto',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
